
const datas = [
    {
        "id": 1,
        "name": "1312 Richmond",
        "location": "Richmond Place 1312, Charlotte, New York",
        "image": "./images/apartment-1.jpeg",
        "door": "Locked",
        "energy_usage": 412,
        "noise_level": 23,
        "is_active": true,
        "owner": "Ethan Stone",
        "owner_location": "+234123546790",
        "checkin": "22 Nov 2018",
        "checkout": "26 Nov 2018",
        "guests": 7,
        "access_code": "5762",
        "owner_code": "1859",
        "cleaner_code": "4565",
        "rating": 4
    },
    {
        "id": 2,
        "name": "6 Fremont Street",
        "location": "6 Fremont Street, Loyalton State, Boston",
        "image": "./images/apartment-2.jpeg",
        "door": "Locked",
        "energy_usage": 592,
        "noise_level": 59,
        "is_active": true,
        "owner": "Ethan Stone",
        "owner_location": "+234123546790",
        "checkin": "22 Nov 2018",
        "checkout": "26 Nov 2018",
        "guests": 7,
        "access_code": "5762",
        "owner_code": "1859",
        "cleaner_code": "4565",
        "rating": 5
    },
    {
        "id": 3,
        "name": "84 Vista Street",
        "location": "84 Vista Street, Encinitas, Washington",
        "image": "./images/apartment-3.jpg",
        "door": "Locked",
        "energy_usage": 592,
        "noise_level": 59,
        "is_active": true,
        "owner": "Ethan Stone",
        "owner_location": "+234123546790",
        "checkin": "22 Nov 2018",
        "checkout": "26 Nov 2018",
        "guests": 7,
        "access_code": "5762",
        "owner_code": "1859",
        "cleaner_code": "4565",
        "rating": 3,
    },
    //inis_active


    {
        "id": 4,
        "name": "Inactive Listing 1",
        "location": "Richmond Place 1312, Charlotte, New York",
        "image": "./images/apartment-1.jpeg",
        "door": "Locked",
        "energy_usage": 412,
        "noise_level": 23,
        "is_active": false,
        "owner": "Ethan Stone",
        "owner_location": "+234123546790",
        "checkin": "22 Nov 2018",
        "checkout": "26 Nov 2018",
        "guests": 7,
        "access_code": "5762",
        "owner_code": "1859",
        "cleaner_code": "4565",
        "rating": 4
    },
    {
        "id": 5,
        "name": "Inactive Listing 2",
        "location": "6 Fremont Street, Loyalton State, Boston",
        "image": "./images/apartment-2.jpeg",
        "door": "Locked",
        "energy_usage": 592,
        "noise_level": 59,
        "is_active": false,
        "owner": "Ethan Stone",
        "owner_location": "+234123546790",
        "checkin": "22 Nov 2018",
        "checkout": "26 Nov 2018",
        "guests": 7,
        "access_code": "5762",
        "owner_code": "1859",
        "cleaner_code": "4565",
        "rating": 5
    },
    {
        "id": 6,
        "name": "Inactive Listing 3",
        "location": "84 Vista Street, Encinitas, Washington",
        "image": "./images/apartment-3.jpg",
        "door": "Locked",
        "energy_usage": 592,
        "noise_level": 59,
        "is_active": false,
        "owner": "Ethan Stone",
        "owner_location": "+234123546790",
        "checkin": "22 Nov 2018",
        "checkout": "26 Nov 2018",
        "guests": 7,
        "access_code": "5762",
        "owner_code": "1859",
        "cleaner_code": "4565",
        "rating": 3,
    }
]


export default datas;